# version: "3.9"

# services:
#   mongo:
#     image: mongo:7
#     container_name: chat-mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

#   backend:
#     build: ./backend
#     ports:
#       - "3001:3001"
#     depends_on:
#       - mongo
#     environment:
#       - MONGO_URL=mongodb://mongo:27017/chatapp
#       - JWT_SECRET=secret123

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

# volumes:
#   mongo_data:

version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat
      - REDIS_HOST=redis
      - JWT_SECRET=secret
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"